export const E = {
  // --- General ---
  legendary:           '\uD83D\uDC8E',
  enormous:            '\u2B50',
  chaos:               '\uD83D\uDD25',
  agitated:            '\uD83C\uDF36\uFE0F',
  disputed:            '\uD83D\uDE24',
  calm:                '\uD83D\uDE10',
  none:                '\uD83D\uDE34',
  winner:              '\uD83C\uDFC6',
  protected:           '\uD83D\uDD12',
  edit:                '\u270F\uFE0F',
  editors:             '\uD83D\uDC65',
  revert:              '\u21A9\uFE0F',
  anon:                '\uD83D\uDC7B',
  watch:               '\uD83D\uDC41\uFE0F',
  minor:               '\u2702\uFE0F',
  vote:                '\u2191',
  checkmark:           '\u2705',
  cross:               '\u274C',
  scales:              '\u2696\uFE0F',
  swords:              '\u2694\uFE0F',
  pointRight:          '\uD83D\uDC49',
  phone:               '\uD83D\uDCF1',
  clipboard:           '\uD83D\uDCCB',
  whatsapp:            '\uD83D\uDCAC',
  twitter:             '\uD83D\uDC26',
  thematic:            '\uD83D\uDDC2\uFE0F',
  finger:              '\u261D\uFE0F',
  handshake:           '\uD83E\uDD1D',
  reload:              '\uD83D\uDD04',
  satellite:           '\uD83D\uDCE1',
  noEntry:             '\uD83D\uDE45',
  arrowLeft:           '\u2190',

  // --- Category icons ---
  catPolitique:        '\uD83C\uDFD7\uFE0F',
  catSport:            '\u26BD',
  catPopCulture:       '\uD83C\uDFAC',
  catScience:          '\uD83D\uDD2C',
  catHistoire:         '\uD83D\uDCDC',
  catReligion:         '\u26A0\uFE0F',
  catTech:             '\uD83D\uDCF1',
  catYtFR:             '\uD83C\uDDEB\uD83C\uDDF7',
  catYtUS:             '\uD83C\uDDFA\uD83C\uDDF8',
  catDefault:          '\uD83D\uDCCC',

  // --- WikiWars icons ---
  pvIcon:              '\uD83D\uDCCA',
  pvViral:             '\uD83D\uDC8E',
  pvMondial:           '\uD83C\uDF0D',
  pvTendance:          '\uD83D\uDCC8',
  pvPopulaire:         '\uD83D\uDC40',
  pvConnu:             '\uD83D\uDCD6',
  pvObscur:            '\uD83C\uDF11',
  wwStar:              '\u2728',
}
