// src/utils/emojis.ts
// NE PAS modifier via l'API GitHub — UTF-8 littéral uniquement

export const E = {
  // Emojis généraux
  legendary:         '💎',
  enormous:          '🌟',
  chaos:             '🔥',
  agitated:          '🌶️',
  disputed:          '😤',
  calm:              '😐',
  none:              '😴',
  winner:            '🏆',
  protected:         '🔒',
  edit:              '✏️',
  editors:           '👥',
  revert:            '↩️',
  anon:              '👻',
  watch:             '👁️',
  minor:             '✂️',
  vote:              '↑',
  checkmark:         '✅',
  cross:             '❌',
  scales:            '⚖️',
  swords:            '⚔️',
  pointRight:        '👉',
  phone:             '📱',
  clipboard:         '📋',
  whatsapp:          '💬',
  twitter:           '🐦',
  thematic:          '🗂️',
  finger:            '☝️',
  handshake:         '🤝',
  reload:            '🔄',
  satellite:         '📡',
  noEntry:           '🙅',
  arrowLeft:         '←',

  // WikiWars emojis
  pvIcon:            '📊',
  pvViral:           '💎',
  pvMondial:         '🌍',
  pvTendance:        '📈',
  pvPopulaire:       '👀',
  pvConnu:           '📖',
  pvObscur:          '🌑',
  wwStar:            '✨',

  // Labels avec accents — dramaScore + DuelCard
  labelLegendary:    'Légendaire',
  labelEnormous:     'Énorme Drama',
  labelChaos:        'Chaos total',
  labelAgitated:     'Agité',
  labelDisputed:     'Disputé',
  labelCalm:         'Calme',
  labelNone:         'Aucun drama',
  labelWinner:       'Plus drama',
  labelProtected:    'Protégé par Wikipedia',
  labelEditors:      'éditeurs',
  labelArticles:     'articles',

  // Labels WikiWars tiers
  labelViral:        'Viral',
  labelMondial:      'Mondial',
  labelTendance:     'Tendance',
  labelPopulaire:    'Populaire',
  labelConnu:        'Connu',
  labelObscur:       'Obscur',

  // Labels WikiWars UI
  wwMostViewed:      'Le plus vu',
  wwVote:            'Voter',
  wwInstruction:     'Lequel a été le plus consulté ces 12 derniers mois ?',
  wwViews12m:        'vues sur 12 mois',
  wwLoading:         'Chargement WikiWars...',
  wwSpecial:         'Special Mode',

  // Labels avec accents — ShareButton
  shareTieHeader:    'WikiDrama — Égalité !',
  shareDuelHeader:   'WikiDrama — Duel Wikipedia',
  shareTieBoth:      "Les deux \u00e0 %score% \u2014 aussi drama l'un que l'autre",
  shareEditions:     'éditions',
  shareEditeurs:     'éditeurs',
  shareEdits30:      'édits/30j',
  shareRight:        "J'avais le bon flair !",
  shareWrong:        'Je me suis fait avoir...',
  shareNoWinner:     'Aucun gagnant, les deux sont légendaires',
  shareFelt:         "Je l'avais senti !",
  sharePartager:     'Partager le duel',
  shareCopied:       'Copié !',
  shareAnnuler:      'Annuler',

  // Labels avec accents — Duel.tsx
  duelThematic:      'Duel Thématique',
  duelControverse:   'controversé',
  duelTapArticle:    "Tape sur l'article le plus controversé",
  duelTie:           "\u00c9galité ! Les deux articles sont aussi drama l'un que l'autre.",
  duelRight:         'Bien joué ! Tu avais le bon flair.',
  duelWrong:         "Raté ! L'autre était plus drama.",
  duelOfflineTitle:  'Pas de connexion',
  duelErrorTitle:    'Chargement impossible',
  duelOfflineMsg:    'Vérifie ta connexion puis réessaie.',
  duelErrorMsg:      'Wikipedia ou XTools ne répond pas. Réessaie dans quelques secondes.',
  duelRetry:         'Réessayer',
  duelBackHome:      "Retour \u00e0 l'accueil",
  duelLoading:       'Chargement du duel...',
  duelLaunch:        'Lancer le duel',
}